authors = ["anders@janmyr.com"]
description = "Gets, wind info from API and publishes it"
language = "go"
manifest_version = 2
name = "windy"
service_id = ""

[local_server]

  [local_server.backends]

    [local_server.backends."open-meteo"]
      url = "https://api.open-meteo.com/"

